# tensorflow fundamental

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.0


In [2]:
vector = tf.constant([9, 6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 6])>

In [4]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2, 3))
random_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [5]:
# random_2 = tf.random.get_global_generator()
random_2 = tf.random.Generator.from_seed(4)
random_2 = random_2.normal(shape=(2, 3))
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ,  0.06987712],
       [-1.4077919 ,  1.0278524 ,  0.27974114]], dtype=float32)>

In [6]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2, 3))

random_1, random_2, random_1 == random_2, random_1 is random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>,
 False)

In [7]:
# Shuffel the order of the tensor
not_shuffled = tf.constant([[10, 5],
                            [4, 8],
                            [7, 9]], dtype=tf.int16)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  5],
       [ 4,  8],
       [ 7,  9]], dtype=int16)>

In [8]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  5],
       [ 4,  8],
       [ 7,  9]], dtype=int16)>

In [9]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  5],
       [ 4,  8],
       [ 7,  9]], dtype=int16)>

# Sheet 2

In [10]:
import torch
import numpy as np
print(torch.__version__)

1.10.1+cpu


In [11]:
tensor_2d = torch.tensor([[2, 5, 6, 7],
                          [4, 7, 2, 6]])
tensor_2d.T

tensor([[2, 4],
        [5, 7],
        [6, 2],
        [7, 6]])

In [12]:
tensor_1 = torch.tensor([4, 6, 3, 6])
tensor_2 = torch.tensor([2, 7, 8, 3])

torch.dot(tensor_1, tensor_2)

tensor(92)

In [13]:
np.random.seed(42)
A = torch.randn(3, 4)
np.random.seed(42)
B = torch.randn(4, 5)

# torch.dot(A, B)
torch.mm(A, B)

tensor([[ 0.9535, -0.1875, -2.2729, -0.4341,  0.3483],
        [-1.3411, -1.1116, -2.8600,  1.2820,  1.8113],
        [-5.1271,  0.9027, -3.0716, -4.0328,  4.3058]])

In [14]:
torch.matmul(A, B)

tensor([[ 0.9535, -0.1875, -2.2729, -0.4341,  0.3483],
        [-1.3411, -1.1116, -2.8600,  1.2820,  1.8113],
        [-5.1271,  0.9027, -3.0716, -4.0328,  4.3058]])

In [15]:
# A*B For Element wise multiplication
# A@B Matrix Multiplication

In [16]:
A@B

tensor([[ 0.9535, -0.1875, -2.2729, -0.4341,  0.3483],
        [-1.3411, -1.1116, -2.8600,  1.2820,  1.8113],
        [-5.1271,  0.9027, -3.0716, -4.0328,  4.3058]])

In [17]:
np.random.seed(42)
A = np.random.randn(3, 4)
np.random.seed(42)
B = np.random.randn(4, 5)

np.dot(A, B)

In [18]:
np.random.seed(42)
A = np.random.randn(3, 4)
np.random.seed(42)
B = np.random.randn(4, 5)

A@B

In [19]:
# 2-d Matrix Dot product

# Sheet 3

In [1]:
import tensorflow as tf
print(tf.__version__)
# Tensor --> Good For GPU and TPU
# numpy_A array --> For CPU

2.8.0


In [2]:
# Create a Tensor By using constant funstion it takes any value i.e. scalar, vector(list), Matrix, Tensor(nd-Matrix)
scalar = tf.constant(4)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=4>, 0)

In [3]:
vector = tf.constant([5, 7, 8])
vector, vector.ndim

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 8], dtype=int32)>, 1)

In [4]:
matrix = tf.constant([[4,6], [6, 7]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 6],
        [6, 7]], dtype=int32)>,
 2)

In [5]:
# A mutable object can be changed after it's created, and an immutable object can't
# constant is an immutable object where as Variable is a mutable object.
changable = tf.Variable([7, 4])
unchangable = tf.constant([7, 4])
changable, unchangable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [6]:
# unchangable[0].assign(5) # Did not change

In [7]:
changable[0].assign(6), changable, unchangable

(<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 4], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [8]:
# Create a random variable
random_x = tf.random.Generator.from_seed(42)
random_x = random_x.normal(shape=(3, 3))
random_x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [9]:
random_y = tf.random.Generator.from_seed(42)
random_y = random_y.normal(shape=(3, 3))
random_y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

In [10]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform(shape=(3, 3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3, 3))

random_1, random_2, random_1 == random_2, random_1 is random_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>,
 False)

In [11]:
# Shuffuled the order of the tensor
unshuffeled = tf.constant([[2, 4, 5],
                           [6, 7, 2],
                           [7, 9, 3]])

tf.random.shuffle(unshuffeled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 9, 3],
       [6, 7, 2],
       [2, 4, 5]], dtype=int32)>

In [12]:
tf.random.shuffle(unshuffeled, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 9, 3],
       [6, 7, 2],
       [2, 4, 5]], dtype=int32)>

In [13]:
tf.random.set_seed(42) 
tf.random.shuffle(unshuffeled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 7, 2],
       [7, 9, 3],
       [2, 4, 5]], dtype=int32)>

In [14]:
# Creating a generator from a seed:
# Reproduciable result because of seed
from_seed = tf.random.Generator.from_seed(425)
from_seed = from_seed.uniform(shape=(2, 2))
from_seed

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5019307 , 0.7626052 ],
       [0.21333694, 0.55127513]], dtype=float32)>

In [15]:
check_state = tf.random.Generator.from_seed(56)
check_state.state

<tf.Variable 'StateVar:0' shape=(3,) dtype=int64, numpy=array([56,  0,  0])>

In [16]:
check_state.state  # Documentation says it's state will change with every refresh But it's not.

<tf.Variable 'StateVar:0' shape=(3,) dtype=int64, numpy=array([56,  0,  0])>

In [17]:
# Creating a generator from a non-deterministic state
# Change with every refresh
without_state = tf.random.Generator.from_non_deterministic_state()
without_state = without_state.uniform(shape=(2, 2))
without_state

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.1388042 , 0.77747095],
       [0.66417766, 0.86078477]], dtype=float32)>

In [18]:
# All the constructors allow explicitly choosing
# an Random-Number-Generation (RNG) algorithm are "philox" and "threefry"
diff_algo = tf.random.Generator.from_seed(seed=456, alg='philox')
diff_algo.uniform(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.78871405, 0.48539102, 0.0492512 , 0.99272   ],
       [0.07170284, 0.90475464, 0.7895447 , 0.8414929 ]], dtype=float32)>

In [19]:
global_gentator = tf.random.get_global_generator()
global_gentator.uniform(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.92042494, 0.80447495],
       [0.9643706 , 0.61824214]], dtype=float32)>

In [20]:
check_seed = tf.constant([[10, 5],
                            [4, 8],
                            [7, 9]], dtype=tf.int16)
tf.random.shuffle(check_seed) # ALways shuffle no use of seed

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[ 7,  9],
       [10,  5],
       [ 4,  8]], dtype=int16)>

In [21]:
tf.random.shuffle(check_seed, seed=42) # Still shuffle even when we apply operation seed

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  5],
       [ 4,  8],
       [ 7,  9]], dtype=int16)>

In [22]:
tf.random.set_seed(42) # Stop shuffle use of global seed
tf.random.shuffle(check_seed) 

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[ 4,  8],
       [ 7,  9],
       [10,  5]], dtype=int16)>

In [23]:
tf.random.set_seed(42) # Use of global and operation seed same time gives different result compare to use of only global seed.
# when be use only operation seed no effect seen. but togather it's show that it has also contributing in seed generation.
tf.random.shuffle(check_seed, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[10,  5],
       [ 4,  8],
       [ 7,  9]], dtype=int16)>

# Other ways to create tensor

In [24]:
# Create a tensor of given shape with element 1.
tf.ones((2, 4)), tf.ones([2, 4])

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)

In [25]:
# Create a tensor of given shape with element 0.
tf.zeros((2, 5)), tf.zeros([2, 5])

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>)

In [26]:
# Also turn numpy into tensors
import numpy as np
numpy_A = np.arange(1, 19, dtype=np.int32)
numpy_A

In [27]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2, 3, 3))
A, B

(<tf.Tensor: shape=(18,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

# Getting Information from tensors

In [28]:
# Create Rank 4 Tensor(4-D Tensor)
rank_4_tensor = tf.ones(shape=(2, 3, 3, 4))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0][1], rank_4_tensor[0, 1]

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>)

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 3, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=72>)

In [31]:
# Get Various attributes of our tensor
print(f'Data type of every element : {rank_4_tensor.dtype}')
print(f'Number of Dimension : {rank_4_tensor.ndim}')
print(f'Shape of tensor : {rank_4_tensor.shape}')
print(f'Element along the 0 axis : {rank_4_tensor.shape[0]}')
print(f'Element along the last axis : {rank_4_tensor.shape[-1]}')
print(f'Total no of element in our tensor : {tf.size(rank_4_tensor)}')

Data type of every element : <dtype: 'float32'>
Number of Dimension : 4
Shape of tensor : (2, 3, 3, 4)
Element along the 0 axis : 2
Element along the last axis : 4
Total no of element in our tensor : 72


# Indexing Tensors
* Tensor can be indexed just like python

In [32]:
# Get the first 2 element of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [33]:
# Get the first element from each dimension from each index except for the final one.
rank_4_tensor[:1, :1, :1], rank_4_tensor[:1, :1, :1, :]

(<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[1., 1., 1., 1.]]]], dtype=float32)>)

In [34]:
# Experiment
rank_4_tensor[:, :1, :2, :3]

<tf.Tensor: shape=(2, 1, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [35]:
# Create a Rank 2 Tensor
rank_2_tensor = tf.ones(shape=(2, 3))
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [36]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [37]:
# Create a random Tensor with a range of value
arank_2_tensor = tf.random.Generator.from_seed(42)
arank_2_tensor = arank_2_tensor.uniform(shape=(5, 5), minval=10, maxval=200, dtype=tf.int32)
arank_2_tensor, arank_2_tensor.shape, arank_2_tensor.ndim, tf.size(arank_2_tensor)

(<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[133, 147, 126,  98, 156],
        [ 61, 151,  97, 182, 107],
        [141,  26,  80, 123,  75],
        [122,  78,  93,  46, 197],
        [ 83,  59, 188,  69, 184]], dtype=int32)>,
 TensorShape([5, 5]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=25>)

In [38]:
# Get the last item of each of row of our rank 2 tensor
arank_2_tensor[:, -1]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([156, 107,  75, 197, 184], dtype=int32)>

In [39]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [40]:
arank_2_tensor[..., tf.newaxis]

<tf.Tensor: shape=(5, 5, 1), dtype=int32, numpy=
array([[[133],
        [147],
        [126],
        [ 98],
        [156]],

       [[ 61],
        [151],
        [ 97],
        [182],
        [107]],

       [[141],
        [ 26],
        [ 80],
        [123],
        [ 75]],

       [[122],
        [ 78],
        [ 93],
        [ 46],
        [197]],

       [[ 83],
        [ 59],
        [188],
        [ 69],
        [184]]], dtype=int32)>

In [41]:
arank_2_tensor[tf.newaxis, ...]

<tf.Tensor: shape=(1, 5, 5), dtype=int32, numpy=
array([[[133, 147, 126,  98, 156],
        [ 61, 151,  97, 182, 107],
        [141,  26,  80, 123,  75],
        [122,  78,  93,  46, 197],
        [ 83,  59, 188,  69, 184]]], dtype=int32)>

In [42]:
arank_2_tensor[:, tf.newaxis, :], arank_2_tensor[:, tf.newaxis]

(<tf.Tensor: shape=(5, 1, 5), dtype=int32, numpy=
 array([[[133, 147, 126,  98, 156]],
 
        [[ 61, 151,  97, 182, 107]],
 
        [[141,  26,  80, 123,  75]],
 
        [[122,  78,  93,  46, 197]],
 
        [[ 83,  59, 188,  69, 184]]], dtype=int32)>,
 <tf.Tensor: shape=(5, 1, 5), dtype=int32, numpy=
 array([[[133, 147, 126,  98, 156]],
 
        [[ 61, 151,  97, 182, 107]],
 
        [[141,  26,  80, 123,  75]],
 
        [[122,  78,  93,  46, 197]],
 
        [[ 83,  59, 188,  69, 184]]], dtype=int32)>)

In [43]:
# Alternative to add dimension
# Add dimension to last.
tf.expand_dims(arank_2_tensor, axis=-1)

<tf.Tensor: shape=(5, 5, 1), dtype=int32, numpy=
array([[[133],
        [147],
        [126],
        [ 98],
        [156]],

       [[ 61],
        [151],
        [ 97],
        [182],
        [107]],

       [[141],
        [ 26],
        [ 80],
        [123],
        [ 75]],

       [[122],
        [ 78],
        [ 93],
        [ 46],
        [197]],

       [[ 83],
        [ 59],
        [188],
        [ 69],
        [184]]], dtype=int32)>

In [44]:
# Add Dimension to front or first
tf.expand_dims(arank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 5, 5), dtype=int32, numpy=
array([[[133, 147, 126,  98, 156],
        [ 61, 151,  97, 182, 107],
        [141,  26,  80, 123,  75],
        [122,  78,  93,  46, 197],
        [ 83,  59, 188,  69, 184]]], dtype=int32)>

In [45]:
# Add Dimension to any position just incress axis value. Make sure that tensor has that amount of dimension
tf.expand_dims(arank_2_tensor, axis=1)

<tf.Tensor: shape=(5, 1, 5), dtype=int32, numpy=
array([[[133, 147, 126,  98, 156]],

       [[ 61, 151,  97, 182, 107]],

       [[141,  26,  80, 123,  75]],

       [[122,  78,  93,  46, 197]],

       [[ 83,  59, 188,  69, 184]]], dtype=int32)>

# Manipulating Tensors (Tensors Operations)
### Basic Operations

In [46]:
# Add values to tensor by '+' or add function
tensor = tf.constant([[2, 5],
                      [6, 9]])
tensor_0 = tf.constant([[3, 5],
                        [4, 7]])
tensor + 10, tf.add(tensor, 10), tf.add(tensor, tensor_0) # Same as numpy 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12, 15],
        [16, 19]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12, 15],
        [16, 19]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 10],
        [10, 16]], dtype=int32)>)

In [47]:
tensor - 3, tf.subtract(tensor, 3), tf.subtract(tensor, tensor_0)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-1,  2],
        [ 3,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-1,  2],
        [ 3,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-1,  0],
        [ 2,  2]], dtype=int32)>)

In [48]:
# First Two Scalar multiplication to matrix
# Last two Element wise Multiplication of Two Matrix with same shape i.e. hadamard product
tensor * 10, tf.multiply(tensor, 10), tensor * tensor_0, tf.multiply(tensor, tensor_0)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 50],
        [60, 90]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 50],
        [60, 90]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6, 25],
        [24, 63]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6, 25],
        [24, 63]], dtype=int32)>)

In [49]:
# Matrix Multiplication

random_matrix_1 = tf.random.Generator.from_seed(seed=55)
random_matrix_1 = random_matrix_1.uniform(shape=(2, 4), minval=1, maxval=30, dtype=tf.int32)
random_matrix_2 = tf.random.Generator.from_seed(seed=55)
random_matrix_2 = random_matrix_2.uniform(shape=(4, 3), minval=10, maxval=50, dtype=tf.int32)


# tf.tensordot(random_matrix_1, random_matrix_2)
tf.matmul(random_matrix_1, random_matrix_2), random_matrix_1@random_matrix_2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1636, 1334, 1424],
        [1286,  887, 1223]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1636, 1334, 1424],
        [1286,  887, 1223]], dtype=int32)>)

In [50]:
number = np.random.randint(low=2, high=89)
random_matrix_3 = tf.constant([6, 8, 8, 8])
random_matrix_4 = tf.constant([0, 6, 3, 7])
tf.tensordot(random_matrix_3,random_matrix_4, axes=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0, 36, 18, 42],
       [ 0, 48, 24, 56],
       [ 0, 48, 24, 56],
       [ 0, 48, 24, 56]], dtype=int32)>

In [51]:
# vector dot product gives a scalar right one.
a = np.array([6, 8, 8, 8])
b = np.array([0, 6, 3, 7])
np.dot(a, b)

128

In [52]:
# 2*2 Matrix dot product is also a scalar but the numpy behave as a Matrix Multiplication. So confusing
# a = np.array([[6, 8, 8, 8],
#               [4, 7, 5, 8]])
# b = np.array([[0, 6, 3, 7],
#               [5, 2, 8, 9]])
# np.dot(a, b)

In [53]:
# Change the shape of matrix
change_shape_matrix = tf.random.uniform(shape=(2, 3), minval=10, maxval=100, dtype=tf.int32)
change_shape_matrix, tf.reshape(change_shape_matrix, shape=(3, 2)), tf.transpose(change_shape_matrix)


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[17, 69, 81],
        [76, 62, 84]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[17, 69],
        [81, 76],
        [62, 84]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[17, 76],
        [69, 62],
        [81, 84]], dtype=int32)>)

# Change the data type of tensor

In [54]:
# Create a tensor with default datatype
a = tf.constant([1.8, 7.5])
b = tf.constant([1, 6])

a.dtype, b.dtype

(tf.float32, tf.int32)

In [55]:
# Change from 32 to 16 (reduced precision)
c = tf.cast(a, dtype=tf.float16)
c

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.8, 7.5], dtype=float16)>

In [56]:
d = tf.cast(c, dtype=tf.int16)
d, d.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 7], dtype=int16)>,
 tf.int16)

# Aggregating Tensors

In [57]:
# Get the absolute value
a = tf.constant([-3, -7, 10, 4, -4])
a, tf.abs(a)

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-3, -7, 10,  4, -4], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  7, 10,  4,  4], dtype=int32)>)

In [2]:
# !pip install --upgrade tensorflow-probability
# !pip install --upgrade tensorflow >= 2.8
# !pip3 install --upgrade pip

In [4]:
import tensorflow_probability as tfp
# Create a random Tensor
np.random.seed(55)
# tf.random.set_seed(55) # This will not work because we are generating no's from numpy.
a = tf.constant(np.random.randint(-60, 60, 40, dtype=np.int32))
# We are converting int to float because reduce_std gives that error -->
# Input must be either real or complex. Received integer type <dtype: 'int32'>.
b = tf.cast(a, dtype=tf.float16)

print(f'Tensor : {a}')
print('***************')
print(f'Absolute Value : {tf.abs(a)}')
print('***************')
print(f'Size : {tf.size(a)}')
print('***************')
print(f'Shape : {a.shape}')
print('***************')
print(f'Tensor Dimension : {a.ndim}')
print('***************')
print(f'Minimum value : {tf.reduce_min(a)}')
print('***************')
print(f'Maximum value : {tf.reduce_max(a)}')
print('***************')
print(f'Mean : {tf.reduce_mean(a)}')
print('***************')
print(f'Standared deviation : {tf.math.reduce_std(a)}')
print('***************')
print(f'Variance : {tfp.stats.variance(a)}')

ModuleNotFoundError: No module named 'tensorflow_probability'

# Find The Positional maximum and minimum

In [5]:
a, tf.argmax(a), tf.argmin(a), tf.size(a), tf.strings.length('Ajay singh')

NameError: name 'a' is not defined

In [63]:
# Create a Random Tensor 
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F, tf.argmax(F), F[tf.argmax(F)], tf.reduce_max(F), F[tf.argmax(F)] == tf.reduce_max(F), F[tf.argmax(F)] is tf.reduce_max(F)
# Why it's false I do not understand

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>,
 False)

# Squeezing a tensor (Removing all single dimension)

In [64]:
# Create a random tensor
tf.random.set_seed(42)
G = tf.random.uniform(shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [65]:
#  To Removes dimensions of size 1 from the shape of a tensor
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One - Hot Encoding Tensors

In [111]:
# Create a list of indices
# labels = ['Cat', 'Dog', 'Snake', 'Human', 'Lion']
labels = [0, 1, 2, 3, 4]
labels_2 = tf.constant([5, 6, 7, 3, 1])

# Check The Result Row wise Not column wise.
tf.one_hot(labels_2, depth=8, axis=0), tf.one_hot(labels_2, depth=8, axis=-1)

(<tf.Tensor: shape=(8, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

In [103]:
labels = [0, 1, 2, 3, 4]

# tf.one_hot(labels, depth=5, on_value='X', off_value='Y')
tf.one_hot(labels, depth=5, on_value=1.2, off_value=0.2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 1.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 1.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 1.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 1.2]], dtype=float32)>

In [118]:
indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices, depth, on_value=1, off_value=0, axis=-1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 1, 0]], dtype=int32)>

# Squaring, Log, Square Root

In [132]:
# Creating a new tensor
# How to make a tf.range function in python check documentation
# In numpy it is np.arange
D = tf.range(1, 100, 5, dtype=tf.int32)
D, tf.square(D), tf.sqrt(tf.cast(D, dtype=tf.float16)), tf.math.log(tf.cast(D, dtype=tf.float16))

(<tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
        86, 91, 96], dtype=int32)>,
 <tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([   1,   36,  121,  256,  441,  676,  961, 1296, 1681, 2116, 2601,
        3136, 3721, 4356, 5041, 5776, 6561, 7396, 8281, 9216], dtype=int32)>,
 <tf.Tensor: shape=(20,), dtype=float16, numpy=
 array([1.   , 2.45 , 3.316, 4.   , 4.582, 5.098, 5.566, 6.   , 6.402,
        6.78 , 7.14 , 7.484, 7.81 , 8.125, 8.43 , 8.72 , 9.   , 9.27 ,
        9.54 , 9.8  ], dtype=float16)>,
 <tf.Tensor: shape=(20,), dtype=float16, numpy=
 array([0.   , 1.792, 2.398, 2.773, 3.045, 3.258, 3.434, 3.584, 3.713,
        3.828, 3.932, 4.023, 4.11 , 4.19 , 4.26 , 4.332, 4.395, 4.453,
        4.51 , 4.562], dtype=float16)>)

In [138]:
# Numpy array
D.numpy(), np.array(D) 

(array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
        86, 91, 96], dtype=int32),
 array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
        86, 91, 96], dtype=int32))

In [143]:
# The Default type of each are different
numpy_J = tf.constant(np.array([3., 4., 5.]))
tensor_J = tf.constant([3., 4., 5.])

# Data type are different
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Dot Product

# Dot Products

In [1]:
import numpy as np
import torch

In [2]:
# Dot product of vactors Numpy
nv1 = np.array([1, 2, 3, 5])
nv2 = np.array([3, 7, 8, 4])

np.dot(nv1, nv2), np.sum(np.multiply(nv1, nv2)), np.sum(nv1*nv2)

(61, 61, 61)

In [3]:
# Dot product of Matrix Numpy
nv1 = np.array([[1, 2, 3, 5],
                [4, 7, 9, 0]])
nv2 = np.array([[3, 7, 8, 4],
                [5, 4, 8, 1]])

# np.dot(nv1, nv2) # Not Working
np.sum(np.multiply(nv1, nv2)), np.sum(nv1*nv2)

(181, 181)

In [4]:
# Dot product of vactor Pytorch
tv1 = torch.tensor([1, 2, 3, 5])
tv2 = torch.tensor([3, 7, 8, 4])

torch.dot(tv1, tv2), torch.sum(torch.multiply(tv1, tv2)), torch.sum(tv1 * tv2)

(tensor(61), tensor(61), tensor(61))

In [5]:
# Dot product of Matrix Pytorch
tv1 = torch.tensor([[1, 2, 3, 5],
                [4, 7, 9, 0]])
tv2 = torch.tensor([[3, 7, 8, 4],
                [5, 4, 8, 1]])

# torch.dot(tv1, tv2) # Also not working
torch.sum(torch.multiply(tv1, tv2)), torch.sum(tv1 * tv2)

(tensor(181), tensor(181))

# Matrix Multiplication

In [6]:
# Matrix multiplication in numpy
A = np.random.randn(3, 4)
B = np.random.randn(4, 3)

A@B, np.matmul(A, B), np.dot(A, B)

(array([[-0.97326462, -0.13365031,  1.00301019],
        [ 2.52547356,  1.06564922,  0.87697421],
        [ 1.54466648,  1.0509429 , -0.14152641]]),
 array([[-0.97326462, -0.13365031,  1.00301019],
        [ 2.52547356,  1.06564922,  0.87697421],
        [ 1.54466648,  1.0509429 , -0.14152641]]),
 array([[-0.97326462, -0.13365031,  1.00301019],
        [ 2.52547356,  1.06564922,  0.87697421],
        [ 1.54466648,  1.0509429 , -0.14152641]]))

In [7]:
# Matrix Multiplication in pytorch
A = torch.randn(3, 4)
B = torch.randn(4, 3)
A@B, torch.matmul(A, B) # torch.dot(A, B) is not working because it is a matrix multiplication.
# but in numpy np.dot() behave different because internally for 2 or more then 2 dimension of matrix 
# it is not work as dot product and work as matrix multiplication.

(tensor([[-1.1269, -6.4191, -3.0875],
         [-0.2290, -2.3087, -1.0362],
         [ 1.6605, -0.2186, -1.1507]]),
 tensor([[-1.1269, -6.4191, -3.0875],
         [-0.2290, -2.3087, -1.0362],
         [ 1.6605, -0.2186, -1.1507]]))

In [8]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

# Tensordot

### Tensordot with Numpy

In [9]:
X = np.array([[1, 2, 3],
              [2, 3, 4]])
Y = np.array([[4, 5],
              [5, 6],
              [6, 7]])

np.dot(X, Y), np.matmul(X, Y), np.tensordot(X, Y, axes=((1), (0))), np.tensordot(X, Y, axes=1)

(array([[32, 38],
        [47, 56]]),
 array([[32, 38],
        [47, 56]]),
 array([[32, 38],
        [47, 56]]),
 array([[32, 38],
        [47, 56]]))

In [10]:
# Create a two vactor for illustration
x = np.array([1,2,3])
y = np.array([4,5,6])

np.tensordot(x, y, axes=0), np.tensordot(x, y, axes=1)

(array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 array(32))

In [11]:
a = np.array([1,2,3]).reshape(3, 1)
b = np.array([4,5,6]).reshape(1, 3)

# In above example axis=0 feel's like it reshape the vactor and then matrix multiplication but it's not
# there is different in calculation for axes=0 for higher dimension.
# for vactors the answer comes same it's confusing.
np.matmul(a, b), np.dot(a, b)

(array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]))

In [12]:
np.tensordot(X, Y, axes=0), np.tensordot(X, Y, axes=0).shape

(array([[[[ 4,  5],
          [ 5,  6],
          [ 6,  7]],
 
         [[ 8, 10],
          [10, 12],
          [12, 14]],
 
         [[12, 15],
          [15, 18],
          [18, 21]]],
 
 
        [[[ 8, 10],
          [10, 12],
          [12, 14]],
 
         [[12, 15],
          [15, 18],
          [18, 21]],
 
         [[16, 20],
          [20, 24],
          [24, 28]]]]),
 (2, 3, 3, 2))

In [39]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.tensordot(x,y, axes = 1), np.tensordot(x,y, axes = (0, 0))

(array(32), array(32))

In [41]:
x = np.array([1,2,3]).reshape(3, 1)
y = np.array([4,5,6]).reshape(3, 1)

x, y, np.tensordot(x, y, axes = (0, 0)), np.tensordot(x,y, axes = (1, 1))

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]),
 array([[32]]),
 array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]))

In [42]:
x = np.array([1,2,3]).reshape(1, 3)
y = np.array([4,5,6]).reshape(1, 3)

x, y, np.tensordot(x, y, axes = (0, 0)), np.tensordot(x,y, axes = (1, 1))

(array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 array([[32]]))

In [35]:
x = np.array([1,2,3]).reshape(1, 3)
y = np.array([4,5,6]).reshape(3, 1)

x, y, np.tensordot(x, y, axes=(1, 0)), np.tensordot(x, y, axes=1)

(array([[1, 2, 3]]),
 array([[4],
        [5],
        [6]]),
 array([[32]]),
 array([[32]]))